### ISSUE TITLE
Plugin doesn't handle DST

### ISSUE THREAD

**Issue by Phlarx** [hmatt1/tm-cotd-countdown#1]
The plugin can be off by 1 hour due to daylight savings times changing out of sync

Original report by Shadefix (Suikertje)#0570 on the Openplanet discord, starting here: https://discord.com/channels/276076890714800129/276076890714800129/905978917784002570
(reported it for them, since they don't have a github account)

Suggestion: add an adjustment Setting that adds/subtracts hours, I guess?

**Comment by hmatt1** [comment]
@Phlarx thank you! I’ll take a look at it

**Comment by hmatt1** [comment]
I merged https://github.com/hmatt1/tm-cotd-countdown/pull/2 to fix this issue, and uploaded version `0.2` to https://openplanet.nl/files/131 with the fix.
